### ISSUE TITLE
Node::equals violates reflexivity?

### ISSUE THREAD

**Issue by rkeeves** [INBPM0420L/homework-project-utils#1]
Hi,

Reflexivity - I suspect - might be violated in `Node::equals` ([see src](https://github.com/INBPM0420L/homework-project-utils/blob/693f14527d4ddb119ec1dcf85b079f414115d6b5/src/main/java/puzzle/solver/Node.java#L103)).

I don't know whether it is some intentional trickery, it just looks suspicious.

(plus a wildcard on line 105 would silence the compiler warning)

Bye,
rkeeves

_P.S.: I really loved University way back when... so  I made a deliberately less oop-ish implementation of this repo's puzzle part which [solves the 3 Jugs Problem](https://github.com/rkeeves/homework-project-utils-psy-wgn/blob/ee4b959acba17fd053597d51f3886d122d42486c/src/main/java/io/github/rkeeves/Main.java#L45-L66) where you can only `pour`, but it can also [solve the 2 Jugs variant](https://github.com/rkeeves/homework-project-utils-psy-wgn/blob/ee4b959acba17fd053597d51f3886d122d42486c/src/main/java/io/github/rkeeves/Main.java#L24-L43) where you can `fill`, `empty` and `pour`. As a bonus I also un-object-oriented some other repos like [rangeutils](https://github.com/rkeeves/closedutils) and [micro-unit](https://github.com/rkeeves/micro-unit) which were a lot of fun. I did these because I miss University very much :)_

**Comment by jeszy75** [comment]
Thank you very much for the feedback. You are right, it is a bug. Fortunately, a harmless one. All the `Node`s generated by the solver are different objects, thus, a `Node` is never compared to itself during the search for a solution.
